
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CARACTERE_ESPECIAL CARDINALIDADE CLASSE NAMESPACE NOME_INDIVIDUO PALAVRA_RESERVADA PROPRIEDADE TIPOprograma : declaracao_classedeclaracao_classe : PALAVRA_RESERVADA CLASSE PALAVRA_RESERVADA  restricoes disjunto individuosrestricoes : PROPRIEDADE PALAVRA_RESERVADA CLASSE\n                  | restricoes_composta\n                  | CARDINALIDADE\n                  | CARACTERE_ESPECIALrestricoes_composta : restricoes CARACTERE_ESPECIAL PROPRIEDADE PALAVRA_RESERVADA CLASSE\n                           | restricoes CARACTERE_ESPECIAL PALAVRA_RESERVADA CARACTERE_ESPECIAL CLASSEdisjunto : PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL CLASSE\n                | individuos : PALAVRA_RESERVADA NOME_INDIVIDUO\n                  | individuos CARACTERE_ESPECIAL NOME_INDIVIDUOdeclaracao_classe : PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL restricoes_defrestricoes_def : CLASSE PALAVRA_RESERVADA restricoes\n                      | restricoes_composta CARACTERE_ESPECIAL restricoesdeclaracao_classe : PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL CARACTERE_ESPECIAL lista_individuos CARACTERE_ESPECIALlista_individuos : NOME_INDIVIDUO\n                         | lista_individuos CARACTERE_ESPECIAL NOME_INDIVIDUOdeclaracao_classe : PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL lista_classeslista_classes : CLASSE\n                      | lista_classes PALAVRA_RESERVADA CLASSE'
    
_lr_action_items = {'PALAVRA_RESERVADA':([0,4,7,8,9,10,11,12,15,19,20,30,32,35,43,45,46,],[3,5,18,21,-4,-5,-6,22,25,28,31,40,-3,-21,-9,-7,-8,]),'$end':([1,2,9,10,11,12,14,15,29,32,33,34,35,36,38,44,45,46,],[0,-1,-4,-5,-6,-20,-13,-19,-2,-3,-14,-16,-21,-15,-11,-12,-7,-8,]),'CLASSE':([3,6,18,21,25,37,40,41,],[4,12,27,32,35,43,45,46,]),'CARACTERE_ESPECIAL':([4,5,6,7,9,10,11,13,16,17,22,23,24,26,27,29,31,32,33,36,38,42,44,45,46,],[6,11,13,20,-4,-5,-6,-6,20,26,11,34,-17,11,37,39,41,-3,20,20,-11,-18,-12,-7,-8,]),'PROPRIEDADE':([5,6,20,22,26,],[8,8,30,8,8,]),'CARDINALIDADE':([5,6,22,26,],[10,10,10,10,]),'NOME_INDIVIDUO':([13,28,34,39,],[24,38,42,44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaracao_classe':([0,],[2,]),'restricoes':([5,6,22,26,],[7,16,33,36,]),'restricoes_composta':([5,6,22,26,],[9,17,9,9,]),'restricoes_def':([6,],[14,]),'lista_classes':([6,],[15,]),'disjunto':([7,],[19,]),'lista_individuos':([13,],[23,]),'individuos':([19,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> declaracao_classe','programa',1,'p_programa','analisadorLexico.py',55),
  ('declaracao_classe -> PALAVRA_RESERVADA CLASSE PALAVRA_RESERVADA restricoes disjunto individuos','declaracao_classe',6,'p_declaracao_classe_primitiva','analisadorLexico.py',60),
  ('restricoes -> PROPRIEDADE PALAVRA_RESERVADA CLASSE','restricoes',3,'p_restricoes','analisadorLexico.py',64),
  ('restricoes -> restricoes_composta','restricoes',1,'p_restricoes','analisadorLexico.py',65),
  ('restricoes -> CARDINALIDADE','restricoes',1,'p_restricoes','analisadorLexico.py',66),
  ('restricoes -> CARACTERE_ESPECIAL','restricoes',1,'p_restricoes','analisadorLexico.py',67),
  ('restricoes_composta -> restricoes CARACTERE_ESPECIAL PROPRIEDADE PALAVRA_RESERVADA CLASSE','restricoes_composta',5,'p_restricoes_composta','analisadorLexico.py',71),
  ('restricoes_composta -> restricoes CARACTERE_ESPECIAL PALAVRA_RESERVADA CARACTERE_ESPECIAL CLASSE','restricoes_composta',5,'p_restricoes_composta','analisadorLexico.py',72),
  ('disjunto -> PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL CLASSE','disjunto',4,'p_disjunto','analisadorLexico.py',76),
  ('disjunto -> <empty>','disjunto',0,'p_disjunto','analisadorLexico.py',77),
  ('individuos -> PALAVRA_RESERVADA NOME_INDIVIDUO','individuos',2,'p_individuos','analisadorLexico.py',81),
  ('individuos -> individuos CARACTERE_ESPECIAL NOME_INDIVIDUO','individuos',3,'p_individuos','analisadorLexico.py',82),
  ('declaracao_classe -> PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL restricoes_def','declaracao_classe',4,'p_declaracao_classe_definida','analisadorLexico.py',87),
  ('restricoes_def -> CLASSE PALAVRA_RESERVADA restricoes','restricoes_def',3,'p_restricoes_def','analisadorLexico.py',91),
  ('restricoes_def -> restricoes_composta CARACTERE_ESPECIAL restricoes','restricoes_def',3,'p_restricoes_def','analisadorLexico.py',92),
  ('declaracao_classe -> PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL CARACTERE_ESPECIAL lista_individuos CARACTERE_ESPECIAL','declaracao_classe',6,'p_declaracao_classe_enumerada','analisadorLexico.py',97),
  ('lista_individuos -> NOME_INDIVIDUO','lista_individuos',1,'p_lista_individuos','analisadorLexico.py',101),
  ('lista_individuos -> lista_individuos CARACTERE_ESPECIAL NOME_INDIVIDUO','lista_individuos',3,'p_lista_individuos','analisadorLexico.py',102),
  ('declaracao_classe -> PALAVRA_RESERVADA CLASSE CARACTERE_ESPECIAL lista_classes','declaracao_classe',4,'p_declaracao_classe_coberta','analisadorLexico.py',107),
  ('lista_classes -> CLASSE','lista_classes',1,'p_lista_classes','analisadorLexico.py',111),
  ('lista_classes -> lista_classes PALAVRA_RESERVADA CLASSE','lista_classes',3,'p_lista_classes','analisadorLexico.py',112),
]
